/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FormasPagamento;

import ConexaoBanco.ConexaoBanco;
import DimensionaImagem.DimensionaImagem;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Marcos
 */
public final class FormasPagamento extends javax.swing.JFrame {
    
    DimensionaImagem dimImagem = new DimensionaImagem();
    ConexaoBanco banco = new ConexaoBanco();
    public java.sql.PreparedStatement ps;
    public java.sql.ResultSet rs;
    public DefaultTableModel modelo;
    public String formaPagamento;

    /**
     * Creates new form FormasPagamento
     */
    public FormasPagamento() {
        initComponents();
        
        lblSituacao.setVisible(false);
        lblSituacao1.setVisible(false);
        
        carregaFormasPagamento();
        
        Font font = new Font("NSimSun", Font.PLAIN, 18);
        
        JTableHeader cabecalhoCliente = tabelaFormasPagamento.getTableHeader();
        cabecalhoCliente.setFont(font);
        
        dimImagem.dimensionaComponentes(lblImagemFundo, "/ControleDeEstoque/Imagens/ImagemFundoCadastro.jpg", 630, 410);
        dimImagem.dimensionaComponentes(lblImagemFundo1, "/ControleDeEstoque/Imagens/ImagemFundoProduto.jpg", 330, 160);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InternalFrameFormaPagamento = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        txtFormaPagamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        lblDataCadastro = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDias = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        lblSituacao1 = new javax.swing.JLabel();
        lblImagemFundo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFormasPagamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisarFormaPagamento = new javax.swing.JTextField();
        btnDados = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblImagemFundo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formas de pagamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        InternalFrameFormaPagamento.setClosable(true);
        InternalFrameFormaPagamento.setTitle("Novo cadastro");
        InternalFrameFormaPagamento.setVisible(false);
        InternalFrameFormaPagamento.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                InternalFrameFormaPagamentoInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        txtFormaPagamento.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jPanel2.add(txtFormaPagamento);
        txtFormaPagamento.setBounds(110, 40, 310, 32);

        jLabel4.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel4.setText("Forma de pagamento");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 10, 170, 30);

        jLabel7.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel7.setText("Tipo");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(280, 100, 36, 30);

        comboTipo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "À vista", "À prazo", "Crédito", "Débito" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });
        jPanel2.add(comboTipo);
        comboTipo.setBounds(280, 130, 290, 32);

        jLabel8.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel8.setText("Cadastrado em");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(450, 10, 130, 30);

        lblDataCadastro.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        lblDataCadastro.setForeground(new java.awt.Color(255, 0, 0));
        lblDataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataCadastro.setText("Data do cadastro");
        jPanel2.add(lblDataCadastro);
        lblDataCadastro.setBounds(450, 40, 150, 30);

        jLabel22.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel22.setText("Código");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(20, 10, 60, 30);

        lblCodigo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 0, 0));
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodigo.setText("Código");
        jPanel2.add(lblCodigo);
        lblCodigo.setBounds(20, 40, 60, 30);
        jPanel2.add(lblImagem);
        lblImagem.setBounds(20, 110, 230, 210);

        btnFechar.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        btnFechar.setText("Sair");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jPanel2.add(btnFechar);
        btnFechar.setBounds(130, 360, 100, 35);

        btnSalvar.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(20, 360, 100, 35);

        jLabel3.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel3.setText("Receber em");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 180, 90, 30);

        txtDias.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        txtDias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtDiasStateChanged(evt);
            }
        });
        jPanel2.add(txtDias);
        txtDias.setBounds(280, 210, 60, 32);

        jLabel2.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel2.setText("Dias");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(360, 210, 50, 30);

        lblSituacao.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        lblSituacao.setForeground(new java.awt.Color(255, 0, 0));
        lblSituacao.setText("Se for à vista, o  recebimento");
        jPanel2.add(lblSituacao);
        lblSituacao.setBounds(280, 260, 280, 30);

        lblSituacao1.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        lblSituacao1.setForeground(new java.awt.Color(255, 0, 0));
        lblSituacao1.setText("é feito na hora.");
        jPanel2.add(lblSituacao1);
        lblSituacao1.setBounds(280, 290, 280, 30);

        lblImagemFundo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jPanel2.add(lblImagemFundo);
        lblImagemFundo.setBounds(0, 0, 630, 410);

        javax.swing.GroupLayout InternalFrameFormaPagamentoLayout = new javax.swing.GroupLayout(InternalFrameFormaPagamento.getContentPane());
        InternalFrameFormaPagamento.getContentPane().setLayout(InternalFrameFormaPagamentoLayout);
        InternalFrameFormaPagamentoLayout.setHorizontalGroup(
            InternalFrameFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InternalFrameFormaPagamentoLayout.setVerticalGroup(
            InternalFrameFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(InternalFrameFormaPagamento);
        InternalFrameFormaPagamento.setBounds(0, 0, 640, 440);

        tabelaFormasPagamento.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        tabelaFormasPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Forma de pagto", "Tipo", "Cod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFormasPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelaFormasPagamento.setRowHeight(25);
        tabelaFormasPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFormasPagamentoMouseClicked(evt);
            }
        });
        tabelaFormasPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaFormasPagamentoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFormasPagamento);
        if (tabelaFormasPagamento.getColumnModel().getColumnCount() > 0) {
            tabelaFormasPagamento.getColumnModel().getColumn(0).setPreferredWidth(500);
            tabelaFormasPagamento.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelaFormasPagamento.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 710, 280);

        jLabel1.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel1.setText("Pesquisar formas de pagamento");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 261, 30);

        txtPesquisarFormaPagamento.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jPanel1.add(txtPesquisarFormaPagamento);
        txtPesquisarFormaPagamento.setBounds(20, 50, 710, 32);

        btnDados.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        btnDados.setText("Dados");
        btnDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnDados);
        btnDados.setBounds(130, 490, 100, 35);

        btnExcluir.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(240, 490, 100, 35);

        btnSair.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(630, 490, 100, 35);

        btnNovo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo);
        btnNovo.setBounds(20, 490, 100, 35);

        lblStatus.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        lblStatus.setText("Formas de pagamento cadastradas: 0");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(20, 420, 350, 30);
        jPanel1.add(lblImagemFundo1);
        lblImagemFundo1.setBounds(380, 380, 330, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
        txtFormaPagamento.setText("");
        txtDias.setValue(1);
        comboTipo.setSelectedIndex(0);
        
        lblCodigo.setText(String.valueOf(getMaxCodigo()+1));
        lblDataCadastro.setText("Data do cadastro");
        
        txtPesquisarFormaPagamento.setEnabled(false);
        tabelaFormasPagamento.setEnabled(false);
        btnNovo.setEnabled(false);
        btnDados.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSair.setEnabled(false);
        
        txtPesquisarFormaPagamento.setEnabled(false);
        tabelaFormasPagamento.setEnabled(false);
        btnNovo.setEnabled(false);
        btnDados.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSair.setEnabled(false);
        
        InternalFrameFormaPagamento.setTitle("Novo cadastro");
        InternalFrameFormaPagamento.setVisible(true);
        
        txtFormaPagamento.grabFocus();
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void InternalFrameFormaPagamentoInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_InternalFrameFormaPagamentoInternalFrameClosed
        
        txtPesquisarFormaPagamento.setEnabled(true);
        tabelaFormasPagamento.setEnabled(true);
        btnNovo.setEnabled(true);
        btnDados.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSair.setEnabled(true);
        
        txtPesquisarFormaPagamento.grabFocus();
        
    }//GEN-LAST:event_InternalFrameFormaPagamentoInternalFrameClosed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed

        if (comboTipo.getSelectedItem().equals("<Selecione>"))
        {
            lblSituacao.setVisible(false);
            lblSituacao1.setVisible(false);
            dimImagem.dimensionaComponentes(lblImagem, "/ControleDeEstoque/Imagens/FormasPagamento.png", 230, 210);
        }
        else if (comboTipo.getSelectedItem().equals("À vista")) 
        {
            lblSituacao.setVisible(true);
            lblSituacao1.setVisible(true);
            txtDias.setValue(1);
            txtDias.setEnabled(false);
            dimImagem.dimensionaComponentes(lblImagem, "/ControleDeEstoque/Imagens/Dinheiro.png", 230, 210);
        }
        else if (comboTipo.getSelectedItem().equals("À prazo")) 
        {
            lblSituacao.setVisible(false);
            lblSituacao1.setVisible(false);
            txtDias.setEnabled(true);
            dimImagem.dimensionaComponentes(lblImagem, "/ControleDeEstoque/Imagens/Cheque.png", 230, 210);
        }
        else if (comboTipo.getSelectedItem().equals("Crédito")) 
        {
            lblSituacao.setVisible(false);
            lblSituacao1.setVisible(false);
            txtDias.setEnabled(true);
            dimImagem.dimensionaComponentes(lblImagem, "/ControleDeEstoque/Imagens/CartaoCredito.png", 230, 210);
        }
        else 
        {
            lblSituacao.setVisible(false);
            lblSituacao1.setVisible(false);
            txtDias.setEnabled(true);
            dimImagem.dimensionaComponentes(lblImagem, "/ControleDeEstoque/Imagens/CartaoDebito.png", 230, 210);
        }
                
    }//GEN-LAST:event_comboTipoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        InternalFrameFormaPagamento.dispose();
        
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        //este método verifica se tem letra no txtDias.. se tiver ele vai retirar
        String carac = "";
        String caracteres = txtDias.getValue().toString();
        for (int i = 0; i <caracteres.length(); i++)
        {
            if (String.valueOf(caracteres.charAt(i)).equals("0") ||
                    String.valueOf(caracteres.charAt(i)).equals("1") ||
                    String.valueOf(caracteres.charAt(i)).equals("2") ||
                    String.valueOf(caracteres.charAt(i)).equals("3") ||
                    String.valueOf(caracteres.charAt(i)).equals("4") ||
                    String.valueOf(caracteres.charAt(i)).equals("5") ||
                    String.valueOf(caracteres.charAt(i)).equals("6") ||
                    String.valueOf(caracteres.charAt(i)).equals("7") ||
                    String.valueOf(caracteres.charAt(i)).equals("8") ||
                    String.valueOf(caracteres.charAt(i)).equals("9"))
            {
                carac = carac + String.valueOf(caracteres.charAt(i));
            }
        }
        int value = Integer.valueOf(carac);
        
        txtDias.setValue(value);
        
        //aqui começa o processo de salvar
        if (txtFormaPagamento.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Preencha o campo Forma de Pagamento!", "Atenção", 
                    JOptionPane.WARNING_MESSAGE, new ImageIcon("/ControleDeEstoque/Imagens/IconeMensagemAviso.png"));
            txtFormaPagamento.grabFocus();
        }
        else if (txtFormaPagamento.getText().length() > 45)
        {
            JOptionPane.showMessageDialog(null, "O campo Forma de Pagamento ultrapassou o limite de caracteres!", "Atenção", 
                    JOptionPane.WARNING_MESSAGE, new ImageIcon("/ControleDeEstoque/Imagens/IconeMensagemAviso.png"));
            txtFormaPagamento.grabFocus();
        }
        else if (comboTipo.getSelectedItem().equals("<Selecione>"))
        {
            JOptionPane.showMessageDialog(null, "Selecione o tipo da forma de pagamento!", "Atenção", 
                    JOptionPane.WARNING_MESSAGE, new ImageIcon("/ControleDeEstoque/Imagens/IconeMensagemAviso.png"));
            comboTipo.grabFocus();
        }
        else
        {
            if (InternalFrameFormaPagamento.getTitle().equals("Novo cadastro"))
            {
                cadastraFormaPagamento(txtFormaPagamento.getText(), 
                        Integer.valueOf(txtDias.getValue().toString()), comboTipo);
                carregaFormasPagamento();
            }
            else
            {
                alterarFormaPagto(txtFormaPagamento.getText(), comboTipo.getSelectedItem().toString(), 
                        Integer.valueOf(txtDias.getValue().toString()), Integer.valueOf(lblCodigo.getText()));
                carregaFormasPagamento();
            }
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        
        int linha = tabelaFormasPagamento.getSelectedRow();
        if (linha < 0)
        {
            JOptionPane.showMessageDialog(null, "Selecione uma forma de pagamento para alterar!", "Atenção", 
                    JOptionPane.WARNING_MESSAGE);
        }
        else
        {            
            carregarDadosFormaPagto(Integer.valueOf(modelo.getValueAt(linha, 2).toString()));
            
            txtPesquisarFormaPagamento.setEnabled(false);
            tabelaFormasPagamento.setEnabled(false);
            btnNovo.setEnabled(false);
            btnDados.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnSair.setEnabled(false);
            
            InternalFrameFormaPagamento.setTitle("Alteração de dados");
            InternalFrameFormaPagamento.setVisible(true);
            
            txtFormaPagamento.grabFocus();
        }
        
    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        int linha = tabelaFormasPagamento.getSelectedRow();
        if (linha <0)
        {
            JOptionPane.showMessageDialog(null, "Selecione uma forma de pagamento para excluir!", "Atenção", 
                    JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if (verificaExclusaoFormaPagto(Integer.valueOf(modelo.getValueAt(linha, 2).toString()))==1)
            {
                JOptionPane.showMessageDialog(null, "Esta é uma forma de pagamento padrão e não poderá ser excluída!", 
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if (verificaExclusaoFormaPagto(Integer.valueOf(modelo.getValueAt(linha, 2).toString()))==2) {
                JOptionPane.showMessageDialog(null, "Esta forma de pagamento está vinculada a uma compra e não poderá ser excluída!", 
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Atenção", 
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (resp == 0)
                {
                    excluirFormaPagto(Integer.valueOf(modelo.getValueAt(linha, 2).toString()));
                    carregaFormasPagamento();
                }
            }
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtDiasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtDiasStateChanged
      
        if (Integer.valueOf(txtDias.getValue().toString()) <1)
        {
            txtDias.setValue(1);
        }
        
    }//GEN-LAST:event_txtDiasStateChanged

    private void tabelaFormasPagamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaFormasPagamentoKeyPressed
        
        int key = evt.getKeyChar();
        if (key == KeyEvent.VK_DELETE)
        {
            btnExcluirActionPerformed(null);
        }
        
    }//GEN-LAST:event_tabelaFormasPagamentoKeyPressed

    private void tabelaFormasPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFormasPagamentoMouseClicked
        
        if (evt.getClickCount() == 2)
        {
            btnDadosActionPerformed(null);
            carregaFormasPagamento();
        }
        
    }//GEN-LAST:event_tabelaFormasPagamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormasPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormasPagamento().setVisible(true);
            }
        });
    }
    
    //METODOS
    
    public void alterarFormaPagto(String formaPagto, String Tipo, int dias, int codigo) {
        
        try
        {
            banco.conexaoBanco();
            ps = banco.con.prepareStatement("update formas_pagamento "
                    + "set Forma_Pagamento = '"+formaPagto+"', "
                    + "Tipo = '"+Tipo+"', "
                    + "Dias = '"+dias+"' "
                    + "where Codigo_Forma_Pagamento = '"+codigo+"'");
            ps.executeUpdate();
            
            ps.close();
            banco.fecharConexaoBanco();
            
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
        
            InternalFrameFormaPagamento.dispose();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }
    
    public int verificaExclusaoFormaPagto(int codFormaPagto) {
        
        int Flag = 0;
        
        try
        {
            banco.conexaoBanco();
            rs = banco.st.executeQuery("select Padrao from formas_pagamento "
                    + "where Codigo_Forma_Pagamento = '"+codFormaPagto+"' "
                    + "and Padrao = 1");
            while (rs.next())
            {
                Flag = 1;
            }
            
            rs = banco.st.executeQuery("select Codigo_Forma_Pagamento from compras "
                    + "where Codigo_Forma_Pagamento = '"+codFormaPagto+"'");
            while (rs.next()) {
                Flag = 2;
            }
            rs.close();
            banco.fecharConexaoBanco();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
        return Flag;
        
    }
    
    public void excluirFormaPagto(int codigo) {
        try
        {            
            banco.conexaoBanco();
            ps = banco.con.prepareStatement("update formas_pagamento set Excluido = 1 "
                    + "where Codigo_Forma_Pagamento = '"+codigo+"'");
            ps.executeUpdate();
            
            ps.close();
            banco.fecharConexaoBanco();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }
    
    public void carregarDadosFormaPagto(int codigo) {
        try
        {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            
            banco.conexaoBanco();
            rs = banco.st.executeQuery("select * from formas_pagamento where "
                    + "Codigo_Forma_Pagamento = '"+codigo+"'");
            while (rs.next())
            {
                lblCodigo.setText(rs.getString("Codigo_Forma_Pagamento"));
                formaPagamento = rs.getString("Forma_Pagamento");
                txtFormaPagamento.setText(rs.getString("Forma_Pagamento"));
                lblDataCadastro.setText(sdf.format(rs.getDate("Data_Cadastro")));
                txtDias.setValue(rs.getInt("Dias"));
                comboTipo.setSelectedItem(rs.getString("Tipo"));
            }
            rs.close();
            banco.fecharConexaoBanco();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }
    
    public void cadastraFormaPagamento(String FormaPagamento, int Dias, javax.swing.JComboBox comboBox) {
        
        try
        {
            banco.conexaoBanco();
            ps = banco.con.prepareStatement("insert into formas_pagamento "
                    + "(Forma_Pagamento, Dias, Tipo) values (?, ?, ?)");
            ps.setString(1, FormaPagamento);
            ps.setInt(2, Dias);
            ps.setString(3, comboBox.getSelectedItem().toString());
            ps.executeUpdate();
            
            ps.close();
            banco.fecharConexaoBanco();
            
            InternalFrameFormaPagamento.dispose();
            
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }
    
    public int getMaxCodigo() {
        int codigo = 0;        
        try 
        {
        banco.conexaoBanco();
        rs = banco.st.executeQuery("select MAX(Codigo_Forma_Pagamento) as CodFormaPagto "
                + "from formas_pagamento");
        while (rs.next()) 
        {
            codigo = rs.getInt("CodFormaPagto");
        }
        rs.close();
        banco.fecharConexaoBanco();
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: "+e,"Atenção", JOptionPane.ERROR_MESSAGE);
        }
        return codigo;
    }
    
    public void carregaFormasPagamento() {
        
        try
        {
            modelo = (DefaultTableModel) tabelaFormasPagamento.getModel();
            modelo.setRowCount(0);
            
            banco.conexaoBanco();
            rs = banco.st.executeQuery("select * from formas_pagamento where Excluido = 0 order by Forma_Pagamento");
            while (rs.next())
            {
                modelo.addRow(new Object[] {
                    rs.getString("Forma_Pagamento"),
                    rs.getString("Tipo"),
                    rs.getInt("Codigo_Forma_Pagamento")
                });
            }
            
            lblStatus.setText("Formas de pagamento cadastradas: "+tabelaFormasPagamento.getRowCount());
            
            rs.close();
            banco.fecharConexaoBanco();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame InternalFrameFormaPagamento;
    private javax.swing.JButton btnDados;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImagemFundo;
    private javax.swing.JLabel lblImagemFundo1;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblSituacao1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tabelaFormasPagamento;
    private javax.swing.JSpinner txtDias;
    private javax.swing.JTextField txtFormaPagamento;
    private javax.swing.JTextField txtPesquisarFormaPagamento;
    // End of variables declaration//GEN-END:variables
}
