/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package LookAndFeel;

import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Marcos
 */
public class LookAndFeel extends javax.swing.JFrame {
    
    private UIManager.LookAndFeelInfo[] looks =   
    UIManager.getInstalledLookAndFeels();  
    private JLabel lbLabel01 = new JLabel("Nome:");  
    private JLabel lbLabel02 = new JLabel("E-mail:");  
    private JTextField jtTexto01 = new JTextField( 10 );  
    private JTextField jtTexto02  = new JTextField( 10 );  
    private JButton jbOk = new JButton("Enviar");  
    private JButton jbLim = new JButton("Limpar");  
    private JRadioButton[] escolha = new JRadioButton[  looks.length ];  
    private ButtonGroup grupo = new ButtonGroup();

    /**
     * Creates new form Teste
     */
    public LookAndFeel() {
        
        super("Selecione um LF");  
        Container c = getContentPane();  
        c.setLayout ( new FlowLayout());  
        c.add(lbLabel01);  
        c.add(jtTexto01);  
        c.add(lbLabel02);  
        c.add(jtTexto02);  
        c.add(jbOk);  
        c.add(jbLim);  
        ItemSelecionado iselect = new ItemSelecionado();  
        for (int i = 0; i < looks.length; i++){  
            escolha[i] = new JRadioButton( looks[i].getName() );  
            escolha[i].addItemListener( iselect );  
            grupo.add( escolha[i] );  
            c.add( escolha[i] );  
        }  
        escolha[0].setSelected( true );  
        setDefaultCloseOperation( EXIT_ON_CLOSE );  
        setSize(200,250);
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    public void atualiza(int i){  
          try {  
          UIManager.setLookAndFeel(looks[i].getClassName());  
          SwingUtilities.updateComponentTreeUI(this);  
          }catch(Exception e) {  
          e.printStackTrace();  
          }  
        }  
  
  private class ItemSelecionado implements ItemListener {  
          public void itemStateChanged( ItemEvent e) {  
            for (int i=0; i < escolha.length; i++){  
            if (escolha[i].isSelected())  
              atualiza(i);  
            }  
          }  
  }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LookAndFeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LookAndFeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LookAndFeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LookAndFeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LookAndFeel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
